SONG_CATALOG = [
    {
        "navidrome_song_id": "enkutatash_song_001",
        "title": "Abebayehosh",
        "artist": "Ethiopian Collective",
        "genre": "Traditional",
        "country": "ethiopia",
        "language": "amharic",
        "release_date": "2026-08-28",
        "play_count_7d": 1200,
        "like_count_7d": 320,
        "skip_rate": 0.08,
        "playlist_id": "holiday_enkutatash_1",
    },
    {
        "navidrome_song_id": "genna_song_002",
        "title": "Genna Mezmur",
        "artist": "Choir Addis",
        "genre": "Gospel",
        "country": "ethiopia",
        "language": "amharic",
        "release_date": "2025-12-20",
        "play_count_7d": 980,
        "like_count_7d": 280,
        "skip_rate": 0.06,
        "playlist_id": "holiday_genna_1",
    },
    {
        "navidrome_song_id": "timket_song_003",
        "title": "Timket Procession",
        "artist": "Axum Band",
        "genre": "Traditional",
        "country": "ethiopia",
        "language": "amharic",
        "release_date": "2026-01-12",
        "play_count_7d": 650,
        "like_count_7d": 190,
        "skip_rate": 0.11,
        "playlist_id": "holiday_timket_1",
    },
    {
        "navidrome_song_id": "global_pop_004",
        "title": "Night Runner",
        "artist": "Nova Lane",
        "genre": "Pop",
        "country": "usa",
        "language": "english",
        "release_date": "2026-02-01",
        "play_count_7d": 3400,
        "like_count_7d": 820,
        "skip_rate": 0.22,
        "playlist_id": None,
    },
    {
        "navidrome_song_id": "eth_jazz_005",
        "title": "Blue Addis",
        "artist": "Mulatu Echo",
        "genre": "Jazz",
        "country": "ethiopia",
        "language": "instrumental",
        "release_date": "2025-11-01",
        "play_count_7d": 890,
        "like_count_7d": 410,
        "skip_rate": 0.05,
        "playlist_id": None,
    },
]
