SONG_CATALOG = [
    {
        "navidrome_song_id": "enkutatash_song_001",
        "title": "Abebayehosh",
        "artist": "Ethiopian Collective",
        "creator_name": "Ethiopian Collective",
        "playlist_title": "Enkutatash Sunrise",
        "genre": "Traditional",
        "country": "ethiopia",
        "language": "amharic",
        "qenet_mode": "Tezeta",
        "release_date": "2026-08-28",
        "tempo": 88,
        "duration": 241,
        "extracted_features": {"energy": 0.54, "danceability": 0.42, "valence": 0.73},
        "play_count_7d": 1200,
        "like_count_7d": 320,
        "skip_rate": 0.08,
        "playlist_id": "holiday_enkutatash_1",
        "save_count": 88,
        "share_count": 22,
        "sales_count": 14,
        "playlist_price": 129,
        "artist_verified": True,
        "is_premium": True,
    },
    {
        "navidrome_song_id": "genna_song_002",
        "title": "Genna Mezmur",
        "artist": "Choir Addis",
        "creator_name": "Choir Addis",
        "playlist_title": "Genna Family Circle",
        "genre": "Gospel",
        "country": "ethiopia",
        "language": "amharic",
        "qenet_mode": "Ambassel",
        "release_date": "2025-12-20",
        "tempo": 96,
        "duration": 265,
        "extracted_features": {"energy": 0.48, "danceability": 0.37, "valence": 0.81},
        "play_count_7d": 980,
        "like_count_7d": 280,
        "skip_rate": 0.06,
        "playlist_id": "holiday_genna_1",
        "save_count": 76,
        "share_count": 19,
        "sales_count": 11,
        "playlist_price": 109,
        "artist_verified": True,
    },
    {
        "navidrome_song_id": "timket_song_003",
        "title": "Timket Procession",
        "artist": "Axum Band",
        "creator_name": "Axum Band",
        "playlist_title": "Timket Procession Essentials",
        "genre": "Traditional",
        "country": "ethiopia",
        "language": "amharic",
        "qenet_mode": "Bati",
        "release_date": "2026-01-12",
        "tempo": 116,
        "duration": 230,
        "extracted_features": {"energy": 0.67, "danceability": 0.51, "valence": 0.62},
        "play_count_7d": 650,
        "like_count_7d": 190,
        "skip_rate": 0.11,
        "playlist_id": "holiday_timket_1",
        "save_count": 61,
        "share_count": 15,
        "sales_count": 9,
        "playlist_price": 99,
        "artist_verified": False,
    },
    {
        "navidrome_song_id": "global_pop_004",
        "title": "Night Runner",
        "artist": "Nova Lane",
        "creator_name": "Nova Lane",
        "genre": "Pop",
        "country": "usa",
        "language": "english",
        "qenet_mode": "Anchihoye",
        "release_date": "2026-02-01",
        "tempo": 124,
        "duration": 214,
        "extracted_features": {"energy": 0.88, "danceability": 0.77, "valence": 0.59},
        "play_count_7d": 3400,
        "like_count_7d": 820,
        "skip_rate": 0.22,
        "playlist_id": None,
        "artist_verified": True,
    },
    {
        "navidrome_song_id": "eth_jazz_005",
        "title": "Blue Addis",
        "artist": "Mulatu Echo",
        "creator_name": "Mulatu Echo",
        "genre": "Jazz",
        "country": "ethiopia",
        "language": "instrumental",
        "qenet_mode": "Tezeta",
        "release_date": "2025-11-01",
        "tempo": 104,
        "duration": 287,
        "extracted_features": {"energy": 0.44, "danceability": 0.36, "valence": 0.47},
        "play_count_7d": 890,
        "like_count_7d": 410,
        "skip_rate": 0.05,
        "playlist_id": None,
        "artist_verified": True,
    },
]
